ROOT_PREFIX    ?= ../../
ROOT_BUILD_DIR ?= $(ROOT_PREFIX)build/

PREFIX    := $(ROOT_PREFIX)backend/city/
BUILD_DIR := $(ROOT_BUILD_DIR)

INCLUDES := -I$(ROOT_PREFIX) -I$(ROOT_PREFIX)backend/city/ -I$(ROOT_PREFIX)ast/city/

include $(ROOT_PREFIX)makefiles/auto_deps.mk
